// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package hms.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the HMS module
	public static java.util.List<hms.proxies.Bed> aCT_AvailableRooms_MF(IContext context, hms.proxies.Hostel _hostel)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Hostel", _hostel == null ? null : _hostel.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("HMS.ACT_AvailableRooms_MF").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> hms.proxies.Bed.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static void aCT_CreateBed(IContext context, hms.proxies.Bed _bed)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Bed", _bed == null ? null : _bed.getMendixObject());
		Core.microflowCall("HMS.ACT_CreateBed").withParams(params).execute(context);
	}
	public static void aCT_CreateNewFacility_MF(IContext context, hms.proxies.Facility _facility)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Facility", _facility == null ? null : _facility.getMendixObject());
		Core.microflowCall("HMS.ACT_CreateNewFacility_MF").withParams(params).execute(context);
	}
	public static void aCT_CreateNewHostelObj_MF(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("HMS.ACT_CreateNewHostelObj_MF").withParams(params).execute(context);
	}
	public static void aCT_CreateNewNotice_MF(IContext context, hms.proxies.NoticeBoard _noticeBoard)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NoticeBoard", _noticeBoard == null ? null : _noticeBoard.getMendixObject());
		Core.microflowCall("HMS.ACT_CreateNewNotice_MF").withParams(params).execute(context);
	}
	public static void aCT_CreateRoom(IContext context, hms.proxies.Room _room)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Room", _room == null ? null : _room.getMendixObject());
		Core.microflowCall("HMS.ACT_CreateRoom").withParams(params).execute(context);
	}
	public static void aCT_DeleteHostel(IContext context, hms.proxies.Hostel _hostel)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Hostel", _hostel == null ? null : _hostel.getMendixObject());
		Core.microflowCall("HMS.ACT_DeleteHostel").withParams(params).execute(context);
	}
	public static void aCT_DeleteTenant_MF(IContext context, hms.proxies.Tenant _tenant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Tenant", _tenant == null ? null : _tenant.getMendixObject());
		Core.microflowCall("HMS.ACT_DeleteTenant_MF").withParams(params).execute(context);
	}
	public static void aCT_NewFacilityOBJ_MF(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("HMS.ACT_NewFacilityOBJ_MF").withParams(params).execute(context);
	}
	public static void aCT_RegistrationTenant(IContext context, hms.proxies.Registration _registration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Registration", _registration == null ? null : _registration.getMendixObject());
		Core.microflowCall("HMS.ACT_RegistrationTenant").withParams(params).execute(context);
	}
	public static void aCT_TenantDepositMoney_Page(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("HMS.ACT_TenantDepositMoney_Page").withParams(params).execute(context);
	}
	public static void aCT_TenantUpdateProfilePage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("HMS.ACT_TenantUpdateProfilePage").withParams(params).execute(context);
	}
	public static java.util.List<hms.proxies.Bed> rET_CurrentHostelBed_MF(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("HMS.RET_CurrentHostelBed_MF").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> hms.proxies.Bed.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<hms.proxies.Facility> rET_CurrentHostelFacilities_MF(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("HMS.RET_CurrentHostelFacilities_MF").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> hms.proxies.Facility.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<hms.proxies.Room> rET_CurrentHostelRoom_MF(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("HMS.RET_CurrentHostelRoom_MF").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> hms.proxies.Room.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<hms.proxies.NoticeBoard> rET_CurrentUserNoticeBoard_MF(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("HMS.RET_CurrentUserNoticeBoard_MF").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> hms.proxies.NoticeBoard.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<hms.proxies.Facility> rET_Facilities_HostelDetail_MF(IContext context, hms.proxies.Hostel _hostel)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Hostel", _hostel == null ? null : _hostel.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("HMS.RET_Facilities_HostelDetail_MF").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> hms.proxies.Facility.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static hms.proxies.Tenant rET_GetCurrentTenant_MF(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("HMS.RET_GetCurrentTenant_MF").withParams(params).execute(context);
		return result == null ? null : hms.proxies.Tenant.initialize(context, result);
	}
	public static java.util.List<hms.proxies.HelperSuperAdminDashboard> rET_SuperAdminDashboardStats_MF(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("HMS.RET_SuperAdminDashboardStats_MF").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> hms.proxies.HelperSuperAdminDashboard.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
}
