// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package hms.proxies;

public class Bed
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bedMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "HMS.Bed";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BedNo("BedNo"),
		Bed_Room("HMS.Bed_Room"),
		Bed_Allotment("HMS.Bed_Allotment");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Bed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Bed(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bedMendixObject)
	{
		if (bedMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, bedMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.bedMendixObject = bedMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Bed.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static hms.proxies.Bed initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return hms.proxies.Bed.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static hms.proxies.Bed initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new hms.proxies.Bed(context, mendixObject);
	}

	public static hms.proxies.Bed load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return hms.proxies.Bed.initialize(context, mendixObject);
	}

	public static java.util.List<hms.proxies.Bed> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> hms.proxies.Bed.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of BedNo
	 */
	public final java.lang.String getBedNo()
	{
		return getBedNo(getContext());
	}

	/**
	 * @param context
	 * @return value of BedNo
	 */
	public final java.lang.String getBedNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BedNo.toString());
	}

	/**
	 * Set value of BedNo
	 * @param bedno
	 */
	public final void setBedNo(java.lang.String bedno)
	{
		setBedNo(getContext(), bedno);
	}

	/**
	 * Set value of BedNo
	 * @param context
	 * @param bedno
	 */
	public final void setBedNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bedno)
	{
		getMendixObject().setValue(context, MemberNames.BedNo.toString(), bedno);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Bed_Room
	 */
	public final hms.proxies.Room getBed_Room() throws com.mendix.core.CoreException
	{
		return getBed_Room(getContext());
	}

	/**
	 * @param context
	 * @return value of Bed_Room
	 * @throws com.mendix.core.CoreException
	 */
	public final hms.proxies.Room getBed_Room(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		hms.proxies.Room result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Bed_Room.toString());
		if (identifier != null) {
			result = hms.proxies.Room.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Bed_Room
	 * @param bed_room
	 */
	public final void setBed_Room(hms.proxies.Room bed_room)
	{
		setBed_Room(getContext(), bed_room);
	}

	/**
	 * Set value of Bed_Room
	 * @param context
	 * @param bed_room
	 */
	public final void setBed_Room(com.mendix.systemwideinterfaces.core.IContext context, hms.proxies.Room bed_room)
	{
		if (bed_room == null) {
			getMendixObject().setValue(context, MemberNames.Bed_Room.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Bed_Room.toString(), bed_room.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Bed_Allotment
	 */
	public final hms.proxies.Allotment getBed_Allotment() throws com.mendix.core.CoreException
	{
		return getBed_Allotment(getContext());
	}

	/**
	 * @param context
	 * @return value of Bed_Allotment
	 * @throws com.mendix.core.CoreException
	 */
	public final hms.proxies.Allotment getBed_Allotment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		hms.proxies.Allotment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Bed_Allotment.toString());
		if (identifier != null) {
			result = hms.proxies.Allotment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Bed_Allotment
	 * @param bed_allotment
	 */
	public final void setBed_Allotment(hms.proxies.Allotment bed_allotment)
	{
		setBed_Allotment(getContext(), bed_allotment);
	}

	/**
	 * Set value of Bed_Allotment
	 * @param context
	 * @param bed_allotment
	 */
	public final void setBed_Allotment(com.mendix.systemwideinterfaces.core.IContext context, hms.proxies.Allotment bed_allotment)
	{
		if (bed_allotment == null) {
			getMendixObject().setValue(context, MemberNames.Bed_Allotment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Bed_Allotment.toString(), bed_allotment.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bedMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final hms.proxies.Bed that = (hms.proxies.Bed) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
