// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package hms.proxies;

public class Facility
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject facilityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "HMS.Facility";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FacilityName("FacilityName"),
		SystemMedia_Facility("HMS.SystemMedia_Facility"),
		Hostel_Facility("HMS.Hostel_Facility");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Facility(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Facility(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject facilityMendixObject)
	{
		if (facilityMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, facilityMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.facilityMendixObject = facilityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Facility.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static hms.proxies.Facility initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return hms.proxies.Facility.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static hms.proxies.Facility initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new hms.proxies.Facility(context, mendixObject);
	}

	public static hms.proxies.Facility load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return hms.proxies.Facility.initialize(context, mendixObject);
	}

	public static java.util.List<hms.proxies.Facility> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> hms.proxies.Facility.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of FacilityName
	 */
	public final java.lang.String getFacilityName()
	{
		return getFacilityName(getContext());
	}

	/**
	 * @param context
	 * @return value of FacilityName
	 */
	public final java.lang.String getFacilityName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FacilityName.toString());
	}

	/**
	 * Set value of FacilityName
	 * @param facilityname
	 */
	public final void setFacilityName(java.lang.String facilityname)
	{
		setFacilityName(getContext(), facilityname);
	}

	/**
	 * Set value of FacilityName
	 * @param context
	 * @param facilityname
	 */
	public final void setFacilityName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String facilityname)
	{
		getMendixObject().setValue(context, MemberNames.FacilityName.toString(), facilityname);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SystemMedia_Facility
	 */
	public final hms.proxies.SystemMedia getSystemMedia_Facility() throws com.mendix.core.CoreException
	{
		return getSystemMedia_Facility(getContext());
	}

	/**
	 * @param context
	 * @return value of SystemMedia_Facility
	 * @throws com.mendix.core.CoreException
	 */
	public final hms.proxies.SystemMedia getSystemMedia_Facility(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		hms.proxies.SystemMedia result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SystemMedia_Facility.toString());
		if (identifier != null) {
			result = hms.proxies.SystemMedia.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SystemMedia_Facility
	 * @param systemmedia_facility
	 */
	public final void setSystemMedia_Facility(hms.proxies.SystemMedia systemmedia_facility)
	{
		setSystemMedia_Facility(getContext(), systemmedia_facility);
	}

	/**
	 * Set value of SystemMedia_Facility
	 * @param context
	 * @param systemmedia_facility
	 */
	public final void setSystemMedia_Facility(com.mendix.systemwideinterfaces.core.IContext context, hms.proxies.SystemMedia systemmedia_facility)
	{
		if (systemmedia_facility == null) {
			getMendixObject().setValue(context, MemberNames.SystemMedia_Facility.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SystemMedia_Facility.toString(), systemmedia_facility.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Hostel_Facility
	 */
	public final java.util.List<hms.proxies.Hostel> getHostel_Facility() throws com.mendix.core.CoreException
	{
		return getHostel_Facility(getContext());
	}

	/**
	 * @param context
	 * @return value of Hostel_Facility
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<hms.proxies.Hostel> getHostel_Facility(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<hms.proxies.Hostel> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Hostel_Facility.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(hms.proxies.Hostel.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Hostel_Facility
	 * @param hostel_facility
	 */
	public final void setHostel_Facility(java.util.List<hms.proxies.Hostel> hostel_facility)
	{
		setHostel_Facility(getContext(), hostel_facility);
	}

	/**
	 * Set value of Hostel_Facility
	 * @param context
	 * @param hostel_facility
	 */
	public final void setHostel_Facility(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<hms.proxies.Hostel> hostel_facility)
	{
		var identifiers = hostel_facility
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Hostel_Facility.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return facilityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final hms.proxies.Facility that = (hms.proxies.Facility) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
