// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package hms.proxies;

public class HelperSuperAdminDashboard
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject helperSuperAdminDashboardMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "HMS.HelperSuperAdminDashboard";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TotalHostels("TotalHostels"),
		TotalCities("TotalCities"),
		TotalTenants("TotalTenants"),
		TotalCarousel("TotalCarousel");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public HelperSuperAdminDashboard(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected HelperSuperAdminDashboard(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject helperSuperAdminDashboardMendixObject)
	{
		if (helperSuperAdminDashboardMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, helperSuperAdminDashboardMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.helperSuperAdminDashboardMendixObject = helperSuperAdminDashboardMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'HelperSuperAdminDashboard.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static hms.proxies.HelperSuperAdminDashboard initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return hms.proxies.HelperSuperAdminDashboard.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static hms.proxies.HelperSuperAdminDashboard initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new hms.proxies.HelperSuperAdminDashboard(context, mendixObject);
	}

	public static hms.proxies.HelperSuperAdminDashboard load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return hms.proxies.HelperSuperAdminDashboard.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TotalHostels
	 */
	public final java.lang.Integer getTotalHostels()
	{
		return getTotalHostels(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalHostels
	 */
	public final java.lang.Integer getTotalHostels(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalHostels.toString());
	}

	/**
	 * Set value of TotalHostels
	 * @param totalhostels
	 */
	public final void setTotalHostels(java.lang.Integer totalhostels)
	{
		setTotalHostels(getContext(), totalhostels);
	}

	/**
	 * Set value of TotalHostels
	 * @param context
	 * @param totalhostels
	 */
	public final void setTotalHostels(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalhostels)
	{
		getMendixObject().setValue(context, MemberNames.TotalHostels.toString(), totalhostels);
	}

	/**
	 * @return value of TotalCities
	 */
	public final java.lang.Integer getTotalCities()
	{
		return getTotalCities(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCities
	 */
	public final java.lang.Integer getTotalCities(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalCities.toString());
	}

	/**
	 * Set value of TotalCities
	 * @param totalcities
	 */
	public final void setTotalCities(java.lang.Integer totalcities)
	{
		setTotalCities(getContext(), totalcities);
	}

	/**
	 * Set value of TotalCities
	 * @param context
	 * @param totalcities
	 */
	public final void setTotalCities(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalcities)
	{
		getMendixObject().setValue(context, MemberNames.TotalCities.toString(), totalcities);
	}

	/**
	 * @return value of TotalTenants
	 */
	public final java.lang.Integer getTotalTenants()
	{
		return getTotalTenants(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalTenants
	 */
	public final java.lang.Integer getTotalTenants(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalTenants.toString());
	}

	/**
	 * Set value of TotalTenants
	 * @param totaltenants
	 */
	public final void setTotalTenants(java.lang.Integer totaltenants)
	{
		setTotalTenants(getContext(), totaltenants);
	}

	/**
	 * Set value of TotalTenants
	 * @param context
	 * @param totaltenants
	 */
	public final void setTotalTenants(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totaltenants)
	{
		getMendixObject().setValue(context, MemberNames.TotalTenants.toString(), totaltenants);
	}

	/**
	 * @return value of TotalCarousel
	 */
	public final java.lang.Integer getTotalCarousel()
	{
		return getTotalCarousel(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCarousel
	 */
	public final java.lang.Integer getTotalCarousel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalCarousel.toString());
	}

	/**
	 * Set value of TotalCarousel
	 * @param totalcarousel
	 */
	public final void setTotalCarousel(java.lang.Integer totalcarousel)
	{
		setTotalCarousel(getContext(), totalcarousel);
	}

	/**
	 * Set value of TotalCarousel
	 * @param context
	 * @param totalcarousel
	 */
	public final void setTotalCarousel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalcarousel)
	{
		getMendixObject().setValue(context, MemberNames.TotalCarousel.toString(), totalcarousel);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return helperSuperAdminDashboardMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final hms.proxies.HelperSuperAdminDashboard that = (hms.proxies.HelperSuperAdminDashboard) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
