// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package hms.proxies;

public class NoticeBoard
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject noticeBoardMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "HMS.NoticeBoard";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NoticeText("NoticeText"),
		Priority("Priority"),
		NoticeBoard_Hostel("HMS.NoticeBoard_Hostel");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public NoticeBoard(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected NoticeBoard(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject noticeBoardMendixObject)
	{
		if (noticeBoardMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, noticeBoardMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.noticeBoardMendixObject = noticeBoardMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'NoticeBoard.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static hms.proxies.NoticeBoard initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return hms.proxies.NoticeBoard.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static hms.proxies.NoticeBoard initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new hms.proxies.NoticeBoard(context, mendixObject);
	}

	public static hms.proxies.NoticeBoard load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return hms.proxies.NoticeBoard.initialize(context, mendixObject);
	}

	public static java.util.List<hms.proxies.NoticeBoard> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> hms.proxies.NoticeBoard.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NoticeText
	 */
	public final java.lang.String getNoticeText()
	{
		return getNoticeText(getContext());
	}

	/**
	 * @param context
	 * @return value of NoticeText
	 */
	public final java.lang.String getNoticeText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NoticeText.toString());
	}

	/**
	 * Set value of NoticeText
	 * @param noticetext
	 */
	public final void setNoticeText(java.lang.String noticetext)
	{
		setNoticeText(getContext(), noticetext);
	}

	/**
	 * Set value of NoticeText
	 * @param context
	 * @param noticetext
	 */
	public final void setNoticeText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String noticetext)
	{
		getMendixObject().setValue(context, MemberNames.NoticeText.toString(), noticetext);
	}

	/**
	 * Set value of Priority
	 * @param priority
	 */
	public final hms.proxies.ENUM_NoticeBoard_Priority getPriority()
	{
		return getPriority(getContext());
	}

	/**
	 * @param context
	 * @return value of Priority
	 */
	public final hms.proxies.ENUM_NoticeBoard_Priority getPriority(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Priority.toString());
		if (obj == null) {
			return null;
		}
		return hms.proxies.ENUM_NoticeBoard_Priority.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Priority
	 * @param priority
	 */
	public final void setPriority(hms.proxies.ENUM_NoticeBoard_Priority priority)
	{
		setPriority(getContext(), priority);
	}

	/**
	 * Set value of Priority
	 * @param context
	 * @param priority
	 */
	public final void setPriority(com.mendix.systemwideinterfaces.core.IContext context, hms.proxies.ENUM_NoticeBoard_Priority priority)
	{
		if (priority != null) {
			getMendixObject().setValue(context, MemberNames.Priority.toString(), priority.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Priority.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of NoticeBoard_Hostel
	 */
	public final java.util.List<hms.proxies.Hostel> getNoticeBoard_Hostel() throws com.mendix.core.CoreException
	{
		return getNoticeBoard_Hostel(getContext());
	}

	/**
	 * @param context
	 * @return value of NoticeBoard_Hostel
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<hms.proxies.Hostel> getNoticeBoard_Hostel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<hms.proxies.Hostel> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.NoticeBoard_Hostel.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(hms.proxies.Hostel.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of NoticeBoard_Hostel
	 * @param noticeboard_hostel
	 */
	public final void setNoticeBoard_Hostel(java.util.List<hms.proxies.Hostel> noticeboard_hostel)
	{
		setNoticeBoard_Hostel(getContext(), noticeboard_hostel);
	}

	/**
	 * Set value of NoticeBoard_Hostel
	 * @param context
	 * @param noticeboard_hostel
	 */
	public final void setNoticeBoard_Hostel(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<hms.proxies.Hostel> noticeboard_hostel)
	{
		var identifiers = noticeboard_hostel
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.NoticeBoard_Hostel.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return noticeBoardMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final hms.proxies.NoticeBoard that = (hms.proxies.NoticeBoard) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
