// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package hms.proxies;

public class Review
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reviewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "HMS.Review";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Comment("Comment"),
		Review_Hostel("HMS.Review_Hostel"),
		Tenant_Review("HMS.Tenant_Review");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Review(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Review(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reviewMendixObject)
	{
		if (reviewMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, reviewMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reviewMendixObject = reviewMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Review.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static hms.proxies.Review initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return hms.proxies.Review.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static hms.proxies.Review initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new hms.proxies.Review(context, mendixObject);
	}

	public static hms.proxies.Review load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return hms.proxies.Review.initialize(context, mendixObject);
	}

	public static java.util.List<hms.proxies.Review> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> hms.proxies.Review.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Comment
	 */
	public final java.lang.String getComment()
	{
		return getComment(getContext());
	}

	/**
	 * @param context
	 * @return value of Comment
	 */
	public final java.lang.String getComment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Comment.toString());
	}

	/**
	 * Set value of Comment
	 * @param comment
	 */
	public final void setComment(java.lang.String comment)
	{
		setComment(getContext(), comment);
	}

	/**
	 * Set value of Comment
	 * @param context
	 * @param comment
	 */
	public final void setComment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String comment)
	{
		getMendixObject().setValue(context, MemberNames.Comment.toString(), comment);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Review_Hostel
	 */
	public final java.util.List<hms.proxies.Hostel> getReview_Hostel() throws com.mendix.core.CoreException
	{
		return getReview_Hostel(getContext());
	}

	/**
	 * @param context
	 * @return value of Review_Hostel
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<hms.proxies.Hostel> getReview_Hostel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<hms.proxies.Hostel> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Review_Hostel.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(hms.proxies.Hostel.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Review_Hostel
	 * @param review_hostel
	 */
	public final void setReview_Hostel(java.util.List<hms.proxies.Hostel> review_hostel)
	{
		setReview_Hostel(getContext(), review_hostel);
	}

	/**
	 * Set value of Review_Hostel
	 * @param context
	 * @param review_hostel
	 */
	public final void setReview_Hostel(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<hms.proxies.Hostel> review_hostel)
	{
		var identifiers = review_hostel
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Review_Hostel.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Tenant_Review
	 */
	public final hms.proxies.Tenant getTenant_Review() throws com.mendix.core.CoreException
	{
		return getTenant_Review(getContext());
	}

	/**
	 * @param context
	 * @return value of Tenant_Review
	 * @throws com.mendix.core.CoreException
	 */
	public final hms.proxies.Tenant getTenant_Review(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		hms.proxies.Tenant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Tenant_Review.toString());
		if (identifier != null) {
			result = hms.proxies.Tenant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Tenant_Review
	 * @param tenant_review
	 */
	public final void setTenant_Review(hms.proxies.Tenant tenant_review)
	{
		setTenant_Review(getContext(), tenant_review);
	}

	/**
	 * Set value of Tenant_Review
	 * @param context
	 * @param tenant_review
	 */
	public final void setTenant_Review(com.mendix.systemwideinterfaces.core.IContext context, hms.proxies.Tenant tenant_review)
	{
		if (tenant_review == null) {
			getMendixObject().setValue(context, MemberNames.Tenant_Review.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Tenant_Review.toString(), tenant_review.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reviewMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final hms.proxies.Review that = (hms.proxies.Review) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
