// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package hms.proxies;

public class Room
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject roomMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "HMS.Room";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RoonNo("RoonNo"),
		TotalBedsCapacity("TotalBedsCapacity"),
		Hostel_Room("HMS.Hostel_Room");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Room(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Room(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject roomMendixObject)
	{
		if (roomMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, roomMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.roomMendixObject = roomMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Room.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static hms.proxies.Room initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return hms.proxies.Room.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static hms.proxies.Room initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new hms.proxies.Room(context, mendixObject);
	}

	public static hms.proxies.Room load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return hms.proxies.Room.initialize(context, mendixObject);
	}

	public static java.util.List<hms.proxies.Room> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> hms.proxies.Room.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of RoonNo
	 */
	public final java.lang.String getRoonNo()
	{
		return getRoonNo(getContext());
	}

	/**
	 * @param context
	 * @return value of RoonNo
	 */
	public final java.lang.String getRoonNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RoonNo.toString());
	}

	/**
	 * Set value of RoonNo
	 * @param roonno
	 */
	public final void setRoonNo(java.lang.String roonno)
	{
		setRoonNo(getContext(), roonno);
	}

	/**
	 * Set value of RoonNo
	 * @param context
	 * @param roonno
	 */
	public final void setRoonNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String roonno)
	{
		getMendixObject().setValue(context, MemberNames.RoonNo.toString(), roonno);
	}

	/**
	 * @return value of TotalBedsCapacity
	 */
	public final java.lang.Integer getTotalBedsCapacity()
	{
		return getTotalBedsCapacity(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalBedsCapacity
	 */
	public final java.lang.Integer getTotalBedsCapacity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalBedsCapacity.toString());
	}

	/**
	 * Set value of TotalBedsCapacity
	 * @param totalbedscapacity
	 */
	public final void setTotalBedsCapacity(java.lang.Integer totalbedscapacity)
	{
		setTotalBedsCapacity(getContext(), totalbedscapacity);
	}

	/**
	 * Set value of TotalBedsCapacity
	 * @param context
	 * @param totalbedscapacity
	 */
	public final void setTotalBedsCapacity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalbedscapacity)
	{
		getMendixObject().setValue(context, MemberNames.TotalBedsCapacity.toString(), totalbedscapacity);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Hostel_Room
	 */
	public final java.util.List<hms.proxies.Hostel> getHostel_Room() throws com.mendix.core.CoreException
	{
		return getHostel_Room(getContext());
	}

	/**
	 * @param context
	 * @return value of Hostel_Room
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<hms.proxies.Hostel> getHostel_Room(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<hms.proxies.Hostel> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Hostel_Room.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(hms.proxies.Hostel.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Hostel_Room
	 * @param hostel_room
	 */
	public final void setHostel_Room(java.util.List<hms.proxies.Hostel> hostel_room)
	{
		setHostel_Room(getContext(), hostel_room);
	}

	/**
	 * Set value of Hostel_Room
	 * @param context
	 * @param hostel_room
	 */
	public final void setHostel_Room(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<hms.proxies.Hostel> hostel_room)
	{
		var identifiers = hostel_room
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Hostel_Room.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return roomMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final hms.proxies.Room that = (hms.proxies.Room) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
