// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package hms.proxies;

public class SystemMedia extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "HMS.SystemMedia";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		SystemMedia_Facility("HMS.SystemMedia_Facility"),
		Hostel_SystemMedia("HMS.Hostel_SystemMedia"),
		Tenant_SystemMedia("HMS.Tenant_SystemMedia");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SystemMedia(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SystemMedia(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject systemMediaMendixObject)
	{
		super(context, systemMediaMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, systemMediaMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'SystemMedia.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static hms.proxies.SystemMedia initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return hms.proxies.SystemMedia.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static hms.proxies.SystemMedia initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new hms.proxies.SystemMedia(context, mendixObject);
	}

	public static hms.proxies.SystemMedia load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return hms.proxies.SystemMedia.initialize(context, mendixObject);
	}

	public static java.util.List<hms.proxies.SystemMedia> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> hms.proxies.SystemMedia.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SystemMedia_Facility
	 */
	public final hms.proxies.Facility getSystemMedia_Facility() throws com.mendix.core.CoreException
	{
		return getSystemMedia_Facility(getContext());
	}

	/**
	 * @param context
	 * @return value of SystemMedia_Facility
	 * @throws com.mendix.core.CoreException
	 */
	public final hms.proxies.Facility getSystemMedia_Facility(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		hms.proxies.Facility result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SystemMedia_Facility.toString());
		if (identifier != null) {
			result = hms.proxies.Facility.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SystemMedia_Facility
	 * @param systemmedia_facility
	 */
	public final void setSystemMedia_Facility(hms.proxies.Facility systemmedia_facility)
	{
		setSystemMedia_Facility(getContext(), systemmedia_facility);
	}

	/**
	 * Set value of SystemMedia_Facility
	 * @param context
	 * @param systemmedia_facility
	 */
	public final void setSystemMedia_Facility(com.mendix.systemwideinterfaces.core.IContext context, hms.proxies.Facility systemmedia_facility)
	{
		if (systemmedia_facility == null) {
			getMendixObject().setValue(context, MemberNames.SystemMedia_Facility.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SystemMedia_Facility.toString(), systemmedia_facility.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Hostel_SystemMedia
	 */
	public final hms.proxies.Hostel getHostel_SystemMedia() throws com.mendix.core.CoreException
	{
		return getHostel_SystemMedia(getContext());
	}

	/**
	 * @param context
	 * @return value of Hostel_SystemMedia
	 * @throws com.mendix.core.CoreException
	 */
	public final hms.proxies.Hostel getHostel_SystemMedia(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		hms.proxies.Hostel result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Hostel_SystemMedia.toString());
		if (identifier != null) {
			result = hms.proxies.Hostel.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Hostel_SystemMedia
	 * @param hostel_systemmedia
	 */
	public final void setHostel_SystemMedia(hms.proxies.Hostel hostel_systemmedia)
	{
		setHostel_SystemMedia(getContext(), hostel_systemmedia);
	}

	/**
	 * Set value of Hostel_SystemMedia
	 * @param context
	 * @param hostel_systemmedia
	 */
	public final void setHostel_SystemMedia(com.mendix.systemwideinterfaces.core.IContext context, hms.proxies.Hostel hostel_systemmedia)
	{
		if (hostel_systemmedia == null) {
			getMendixObject().setValue(context, MemberNames.Hostel_SystemMedia.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Hostel_SystemMedia.toString(), hostel_systemmedia.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Tenant_SystemMedia
	 */
	public final hms.proxies.Tenant getTenant_SystemMedia() throws com.mendix.core.CoreException
	{
		return getTenant_SystemMedia(getContext());
	}

	/**
	 * @param context
	 * @return value of Tenant_SystemMedia
	 * @throws com.mendix.core.CoreException
	 */
	public final hms.proxies.Tenant getTenant_SystemMedia(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		hms.proxies.Tenant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Tenant_SystemMedia.toString());
		if (identifier != null) {
			result = hms.proxies.Tenant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Tenant_SystemMedia
	 * @param tenant_systemmedia
	 */
	public final void setTenant_SystemMedia(hms.proxies.Tenant tenant_systemmedia)
	{
		setTenant_SystemMedia(getContext(), tenant_systemmedia);
	}

	/**
	 * Set value of Tenant_SystemMedia
	 * @param context
	 * @param tenant_systemmedia
	 */
	public final void setTenant_SystemMedia(com.mendix.systemwideinterfaces.core.IContext context, hms.proxies.Tenant tenant_systemmedia)
	{
		if (tenant_systemmedia == null) {
			getMendixObject().setValue(context, MemberNames.Tenant_SystemMedia.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Tenant_SystemMedia.toString(), tenant_systemmedia.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final hms.proxies.SystemMedia that = (hms.proxies.SystemMedia) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
